spring.application.name=produto-service
server.port=8082

# Cada microsservico tem o seu proprio banco de dados (aqui, um banco Mongo so para produto)
spring.data.mongodb.uri=mongodb://localhost:27017/produto_db
