spring.application.name=cliente-service
server.port=8081

# Cada microsservico tem o seu proprio banco de dados (aqui, um banco Mongo so para cliente)
spring.data.mongodb.uri=mongodb://localhost:27017/cliente_db
